# Generated by Django 2.2.2 on 2019-07-14 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('discount', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('discount_card', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('sex', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('date_of_created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('web_page', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('requisite_organization_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('requisite_organization_number', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('bank_requisite', models.CharField(blank=True, default=None, max_length=18, null=True)),
                ('legal_address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('actual_address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
