# Generated by Django 2.2.2 on 2019-07-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_auto_20190722_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
