# Generated by Django 2.2.2 on 2019-07-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0004_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pay',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
