# Generated by Django 2.2.2 on 2019-07-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0006_auto_20190722_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='prepayment',
            field=models.IntegerField(default=0),
        ),
    ]
