# Generated by Django 2.2.2 on 2019-07-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Катерогия',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('barcode', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='Image_of_products')),
                ('unit', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('purchase_price', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('markup', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('vat', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('categories_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('shop', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
                ('suppliers_name', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='counterparties.Supplier')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('items', models.ManyToManyField(blank=True, to='product.CartItem')),
            ],
        ),
    ]
