# Generated by Django 2.2.2 on 2019-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190717_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
