# Generated by Django 2.2.2 on 2019-07-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190718_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='counter',
        ),
    ]
