# Generated by Django 2.2.2 on 2019-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190718_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='createDate',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
