# Generated by Django 2.2.2 on 2019-07-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190718_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Проданный товар', 'verbose_name_plural': 'Проданные товары'},
        ),
        migrations.AddField(
            model_name='cart',
            name='total_product',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
