# Generated by Django 2.2.2 on 2019-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190718_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_product',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
