# Generated by Django 2.2.2 on 2019-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190718_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
