# Generated by Django 2.2.2 on 2019-07-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
