# Generated by Django 2.2.2 on 2019-07-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20190722_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='get_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
