# Generated by Django 2.2.2 on 2019-07-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='Shops_images')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
